import PrimeGapNormality.Prime.CoreCalibratedRectanglePrecision
import PrimeGapNormality.Prime.CoreCalibratedRectanglePrecisionSharp
import PrimeGapNormality.Prime.CoreGeneralReferenceSharp

/-!
# Consolidated audit for the remaining sharp endpoints

This combines the complete check and transitive-axiom surfaces of
`CoreCalibratedRectanglePrecisionAudit`,
`CoreCalibratedRectanglePrecisionSharpAudit`, and
`CoreGeneralReferenceSharpAudit` while importing their proof modules directly.
The shared open-rectangle endpoint is checked once below.
-/

namespace PrimeGapNormality.Prime

#check @CoreCalibratedFactorialRectangle.lateRootLayer_descFactorial_moment_le
#print axioms CoreCalibratedFactorialRectangle.lateRootLayer_descFactorial_moment_le
#check @CoreCalibratedFactorialRectangle.auxiliaryLayer_factorial_rectangle_le
#print axioms CoreCalibratedFactorialRectangle.auxiliaryLayer_factorial_rectangle_le

#check @CoreSelbergRectanglePrecision.eventually_candidateCap_le_three
#print axioms CoreSelbergRectanglePrecision.eventually_candidateCap_le_three

#check @CoreCalibratedRectanglePrecision.eventually_scaled_retention_le_twenty_ninths
#print axioms CoreCalibratedRectanglePrecision.eventually_scaled_retention_le_twenty_ninths
#check @CoreCalibratedRectanglePrecision.eventually_layer_rectangle_precision
#print axioms CoreCalibratedRectanglePrecision.eventually_layer_rectangle_precision
#check @CoreCalibratedRectanglePrecision.eventually_completed_rectangle_precision
#print axioms CoreCalibratedRectanglePrecision.eventually_completed_rectangle_precision
#check @CoreCalibratedRectanglePrecision.tendsto_precisionRectangleError_zero
#print axioms CoreCalibratedRectanglePrecision.tendsto_precisionRectangleError_zero
#check @CoreCalibratedRectanglePrecision.eventually_profileLaw_rectangle_precision
#print axioms CoreCalibratedRectanglePrecision.eventually_profileLaw_rectangle_precision
#check @CoreCalibratedRectanglePrecision.weak_limit_open_rectangle_precision
#print axioms CoreCalibratedRectanglePrecision.weak_limit_open_rectangle_precision
#check @CoreCalibratedRectanglePrecision.weak_limit_le_volume_from_precision
#print axioms CoreCalibratedRectanglePrecision.weak_limit_le_volume_from_precision
#check @CoreCalibratedRectanglePrecision.weak_limit_absolutelyContinuous_from_precision
#print axioms CoreCalibratedRectanglePrecision.weak_limit_absolutelyContinuous_from_precision

#check @CoreRectangleMeasureDominationSharp.measure_le_diameter_power_sharp
#print axioms CoreRectangleMeasureDominationSharp.measure_le_diameter_power_sharp
#check @CoreRectangleMeasureDominationSharp.le_volume_of_open_rectangle_bound_sharp
#print axioms CoreRectangleMeasureDominationSharp.le_volume_of_open_rectangle_bound_sharp

#check @CoreCalibratedRectanglePrecisionSharp.weak_limit_le_volume_precision_sharp
#print axioms CoreCalibratedRectanglePrecisionSharp.weak_limit_le_volume_precision_sharp
#check @CoreCalibratedRectanglePrecisionSharp.weak_limit_absolutelyContinuous_precision_sharp
#print axioms CoreCalibratedRectanglePrecisionSharp.weak_limit_absolutelyContinuous_precision_sharp

#check @CoreGeneralReferenceSharp.exists_fullWindow_reference
#print axioms CoreGeneralReferenceSharp.exists_fullWindow_reference
#check @CoreGeneralReferenceSharp.exists_reference_for_residue_limits
#print axioms CoreGeneralReferenceSharp.exists_reference_for_residue_limits
#check @CoreGeneralReferenceSharp.residue_limit_le_reference
#print axioms CoreGeneralReferenceSharp.residue_limit_le_reference
#check @CoreGeneralReferenceSharp.residue_limit_le_of_complexPatternS
#print axioms CoreGeneralReferenceSharp.residue_limit_le_of_complexPatternS
#check @CoreGeneralReferenceSharp.residue_limit_le_of_realCutoff
#print axioms CoreGeneralReferenceSharp.residue_limit_le_of_realCutoff

end PrimeGapNormality.Prime
