import PrimeGapNormality.Prime.CoreRoughScaleDilation

namespace PrimeGapNormality.Prime.CoreRoughScaleDilationAudit

#check @CoreRoughScaleDilation.eventually_realEndpointCutoff_mono
#check @CoreRoughScaleDilation.tendsto_gapScale_two_ratio_one
#check @CoreRoughScaleDilation.tendsto_gapScale_floor_dilation_ratio_one
#check @CoreRoughScaleDilation.tendsto_gapScale_nat_dilation_ratio_one
#check @CoreRoughScaleDilation.tendsto_realEndpoint_div_natAnchor_one
#check @CoreRoughScaleDilation.tendsto_gapScale_real_dilation_ratio_one

#print axioms CoreRoughScaleDilation.eventually_realEndpointCutoff_mono
#print axioms CoreRoughScaleDilation.tendsto_gapScale_two_ratio_one
#print axioms CoreRoughScaleDilation.tendsto_gapScale_floor_dilation_ratio_one
#print axioms CoreRoughScaleDilation.tendsto_gapScale_nat_dilation_ratio_one
#print axioms CoreRoughScaleDilation.tendsto_realEndpoint_div_natAnchor_one
#print axioms CoreRoughScaleDilation.tendsto_gapScale_real_dilation_ratio_one

end PrimeGapNormality.Prime.CoreRoughScaleDilationAudit
